### ISSUE TITLE
Add a readme

### ISSUE THREAD

**Issue by dumptyd** [avinassh/cemetery.io#3]
- Describe what this project is.
- Add instructions about how to add your own cemetery.

**Comment by dumptyd** [comment]
goddamnit @avinassh, do it man 😐

**Comment by dumptyd** [comment]
@oxalorg you wanna take this up? 😛

**Comment by oxalorg** [comment]
Sure. I'll take this up.

**Comment by ashubly25** [comment]
I am in love with this repo. This is pure shitposting right.

**Comment by avinassh** [comment]
@ashubly25 nope. this is not shit posting. this is a serious project.
